### ISSUE TITLE
数组格式参数的优化

### ISSUE THREAD

**Issue by Greyh4t** [guonaihong/clop#57]
现在添加数组格式的参数只能通过 `-l 123 -l 456`这种多次添加的方式实现，当数组内容比较多的时候很麻烦，是否可以支持 `-l 123 456`或 `-l 123,456` 这种方式呢

**Comment by guonaihong** [comment]
现在就支持这个功能。加个greedy属性就可以。
```go
package main

import (
    "fmt"

    "github.com/guonaihong/clop"
)

type test struct {
    A []int `clop:"-a;greedy" usage:"test array"`
    B int   `clop:"-b" usage:"test int"`
}

func main() {
    a := &test{}
    clop.Bind(a)
    fmt.Printf("%#v\n", a)
}

```
* 运行
```
./use_array -a 12 34 56 78 -b 100
```
* 输出
```
&main.test{A:[]int{12, 34, 56, 78}, B:100}
```

**Comment by Greyh4t** [comment]
> 现在就支持这个功能。加个greedy属性就可以。
> 
> ```go
> package main
> 
> import (
>     "fmt"
> 
>     "github.com/guonaihong/clop"
> )
> 
> type test struct {
>     A []int `clop:"-a;greedy" usage:"test array"`
>     B int   `clop:"-b" usage:"test int"`
> }
> 
> func main() {
>     a := &test{}
>     clop.Bind(a)
>     fmt.Printf("%#v\n", a)
> }
> ```
> 
> * 运行
> 
> ```
> ./use_array -a 12 34 56 78 -b 100
> ```
> 
> * 输出
> 
> ```
> &main.test{A:[]int{12, 34, 56, 78}, B:100}
> ```

啊 这样啊 感谢，手册里没看到这个，这样就方便多了

**Comment by guonaihong** [comment]
客气，我晚上更新下文档。
