### ISSUE TITLE
如何实现--version的功能

### ISSUE THREAD

**Issue by Greyh4t** [guonaihong/clop#88]
使用中发现如果存在多个参数，并且有其他参数指定了required校验，当这个参数为空的情况下，直接就报错了，--version参数被忽略了

**Comment by guonaihong** [comment]
可否发个最小化复现的代码, 我看下.

**Comment by Greyh4t** [comment]
```go
package main

import (
	"fmt"
	"log"

	"github.com/guonaihong/clop"
)

var (
	version = "0.0.1"
)

type Config struct {
	Addr    string `clop:"--addr" usage:"addr" valid:"required"`
	Version bool   `clop:"-v; --version" usage:"version"`
}

func main() {
	var cfg Config
	err := clop.Bind(&cfg)
	if err != nil {
		log.Fatal(err)
	}
	if cfg.Version {
		fmt.Println(version)
		return
	}
}
```
用 `./cloptest -v` 调用会提示 "--addr must have a value!"

**Comment by guonaihong** [comment]
目前语义是这么设计的. --addr 后面必须要有值. 你不设置就会有 "--addr must have a value!" , 如果--addr不是必须的, 就把
valid:"required" 去掉就行.

**Comment by Greyh4t** [comment]
但是这个校验是需要的，在这种情况下我想加入一个--version的参数，用来打印这个程序的版本，按理说这个参数的优先级跟--help应该是一样的，目前是不是不支持这样的功能

**Comment by guonaihong** [comment]
version有设计. 只在usage里面会打印
```go
package main

import (
	"fmt"
	"log"

	"github.com/guonaihong/clop"
)

var (
	version = "0.0.1"
)

type Config struct {
	Addr    string `clop:"--addr" usage:"addr" valid:"required"`
	Version string `clop:"version=0.0.3" usage:"version"`
}

func main() {
	var cfg Config
	err := clop.Bind(&cfg)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(cfg.Version)
	/*
		if cfg.Version {
			fmt.Println(version)
			return
		}
	*/
}
```

**Comment by guonaihong** [comment]
你先用着看看.  能不能满足需求, 不行. 我重新设计下这个功能点.

**Comment by Greyh4t** [comment]
嗯嗯，谢谢，这个刚看源码发现了，我先用这个。但是看命令行程序大多数都是可以单独设置--version参数的，所以感觉还是有这个功能比较好。是不是可以添加个类似优先级一样的标记，有这个标记的话与--help一样的优先级来处理呢，或者有更好的方式也行

**Comment by Greyh4t** [comment]
目前的这种模式有个问题，就是走代码发布流程的时候，代码里version是留空的，每次编译的时候通过 `-ldflags="-X main.version=${VERSION}` 这种方式传进去，这种需求没办法实现

**Comment by guonaihong** [comment]
> 目前的这种模式有个问题，就是走代码发布流程的时候，代码里version是留空的，每次编译的时候通过 `-ldflags="-X main.version=${VERSION}` 这种方式传进去，这种需求没办法实现

那伪代码设计如下: 支持每次在编译的时候指定.
```go
package main

import (
	"fmt"
	"log"

	"github.com/guonaihong/clop"
)

var (
	version = "0.0.1"
)

type Config struct {
	Addr    string `clop:"--addr" usage:"addr" valid:"required"`
}

func (c *Config) Version string {
    return version
}

func main() {
	var cfg Config
	err := clop.Bind(&cfg)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(cfg.Version)
	/*
		if cfg.Version {
			fmt.Println(version)
			return
		}
	*/
}
```

**Comment by Greyh4t** [comment]
> 

这样貌似可以， 不过我觉得这个方法名字可以改一下，可以改成clopVersion之类的，防止如果有真的Version函数需求的话冲突，然后在这个函数里返回version的信息，当用-v或者--version参数调用程序的时候就自动输出这个函数里的内容我感觉就可以了

**Comment by Greyh4t** [comment]
或者我觉得给Clop结构体实现SetVersion方法？然后--version参数的时候直接输出SetVersion设置进去的值怎么样呢
伪代码
```go
package main

import (
	"log"

	"github.com/guonaihong/clop"
)

const (
	version = "0.0.1"
)

type Config struct {
	Addr string `clop:"--addr" usage:"addr" valid:"required"`
}

func main() {
	clop.SetVersion(version)
	var cfg Config
	err := clop.Bind(&cfg)
	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by guonaihong** [comment]
我昨天撸下思路, 这几天工作比较忙.

**Comment by guonaihong** [comment]
使用下v0.2.3版本就可以了.

**Comment by guonaihong** [comment]
先关闭了, 如果有问题可重新打开.

**Comment by Greyh4t** [comment]
> 先关闭了, 如果有问题可重新打开.

试了一下version功能有了，感谢。但是有一个问题，现在version功能会默认强制输出程序路径，但是version信息本身就是用户自己调用程序才输出的，再输出一遍程序名有点重复。
这块儿感觉完全让用户自定义是不是更好，我看了好几个程序的version输出信息，都没有直接输出当前程序路径的，都是自己构造version信息输出
包括python，go，wget，axel等，都不输出当前程序的名字

**Comment by Greyh4t** [comment]
```go
// 显示version信息
func (c *Clop) showVersion() {
	fmt.Fprint(c.w, c.version)
	if c.exit {
		os.Exit(0)
	}
}
```
整个version信息都交给用户自定义，包括换行啥的，这样感觉还行？

**Comment by guonaihong** [comment]
@Greyh4t 没问题, 你提个pr, 我合并下.

**Comment by guonaihong** [comment]
https://github.com/guonaihong/clop/blob/master/help_tmpl.go#L67 @Greyh4t 这个地方也要修改下.

**Comment by Greyh4t** [comment]
> @Greyh4t 这种输出是预期的吗? 如果是预期的, 我就打上0.2.4的tag
> 
> ```shell
> ./main -h
> ```
> 
> ```
> ./main 0.0.2
> 演示SetVersion的demo
> 
> Usage:
>     ./main [Options]
> 
> Options:
>     --addr          addr
>     -V,--version    print version information
>     -h,--help       print the help information
> ```
> 
> ```
> For more information try --help
> ➜  use-clop ./main -V
> 0.0.2%
> ```
> 
> ```go
> package main
> 
> import (
> 	"github.com/guonaihong/clop"
> )
> 
> var (
> 	version = "0.0.2"
> )
> 
> type Config struct {
> 	Addr string `clop:"--addr" usage:"addr" valid:"required"`
> }
> 
> func main() {
> 	var cfg Config
> 	clop.SetVersion(version)
> 	clop.SetAbout("演示SetVersion的demo")
> 	clop.MustBind(&cfg)
> }
> ```

试了一下version没问题了，不过about的部分还是会输出程序名，不然这块我再改改，改成这块也由用户自定义，没设置就不输出？

**Comment by guonaihong** [comment]
那你修改下help_tmpl.go大约在30行的地方，搜索下ProcName。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月5日(周四) 晚上11:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [guonaihong/clop] 如何实现--version的功能 (Issue #88)




  
@Greyh4t 这种输出是预期的吗? 如果是预期的, 我就打上0.2.4的tag
 ./main -h
 ./main 0.0.2 演示SetVersion的demo Usage:     ./main [Options] Options:     --addr          addr     -V,--version    print version information     -h,--help       print the help information  For more information try --help ➜  use-clop ./main -V 0.0.2%  package main import ( "github.com/guonaihong/clop" ) var ( version = "0.0.2" ) type Config struct { Addr string `clop:"--addr" usage:"addr" valid:"required"` } func main() { var cfg Config clop.SetVersion(version) clop.SetAbout("演示SetVersion的demo") clop.MustBind(&amp;cfg) }
  
试了一下version没问题了，不过about的部分还是会输出程序名，不然这块我再改改，改成这块也由用户自定义，没设置就不输出？
